export const ASYNC_START = "ASYNC_START";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT = "LOGOUT";
export const GET_EXERCISE_CATEGORIES = "GET_EXERCISE_CATEGORIES";
export const GET_EXERCISES = "GET_EXERCISES";
export const GET_USER_WORKOUTS = "GET_USER_WORKOUTS";
export const UPDATE_CURRENT_NEW_ROUTINE = "UPDATE_CURRENT_NEW_ROUTINE";
export const SET_CURRENT_NEW_ROUTINE = "SET_CURRENT_NEW_ROUTINE";
export const UPDATE_CURRENT_ROUTINE_TITLE = "UPDATE_CURRENT_ROUTINE_TITLE";
export const POST_NEW_ROUTINE = "POST_NEW_ROUTINE";
export const ADD_EXERCISE_TO_CURRENT_ROUTINE =
  "ADD_EXERCISE_TO_CURRENT_ROUTINE";
export const SET_CURRENT_WORKOUT = "SET_CURRENT_WORKOUT";
export const GET_CURRENT_WORKOUT = "GET_CURRENT_WORKOUT";
