// Async types
export const ASYNC_START = "ASYNC_START";
export const ASYNC_END = "ASYNC_END";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT = "LOGOUT";

// Exercise Category types
export const GET_EXERCISE_CATEGORIES = "GET_EXERCISE_CATEGORIES";

// Exercise types
export const ASYNC_START_EXERCISES = "ASYNC_START_EXERCISES";
export const ASYNC_ERROR_EXERCISES = "ASYNC_ERROR_EXERCISES";
export const GET_EXERCISES = "GET_EXERCISES";
export const ADD_EXERCISE = "ADD_EXERCISE";

// Routine types

export const ASYNC_START_ROUTINES = "ASYNC_START_ROUTINES";
export const ASYNC_ERROR_ROUTINES = "ASYNC_ERROR_ROUTINES";
export const UPDATE_CURRENT_NEW_ROUTINE = "UPDATE_CURRENT_NEW_ROUTINE";
export const SET_CURRENT_NEW_ROUTINE = "SET_CURRENT_NEW_ROUTINE";
export const UPDATE_CURRENT_ROUTINE_TITLE = "UPDATE_CURRENT_ROUTINE_TITLE";
export const POST_NEW_ROUTINE = "POST_NEW_ROUTINE";
export const ADD_EXERCISE_TO_CURRENT_ROUTINE =
  "ADD_EXERCISE_TO_CURRENT_ROUTINE";
export const GET_ROUTINES = "GET_ROUTINES";

// Current Workout / Workout types
export const GET_USER_WORKOUTS = "GET_USER_WORKOUTS";
export const SET_CURRENT_WORKOUT = "SET_CURRENT_WORKOUT";
export const GET_CURRENT_WORKOUT = "GET_CURRENT_WORKOUT";
export const NO_CURRENT_WORKOUT = "NO_CURRENT_WORKOUT";
export const ADD_EXERCISE_TO_CURRENT_WORKOUT =
  "ADD_EXERCISE_TO_CURRENT_WORKOUT";
export const FINISH_WORKOUT = "FINISH_WORKOUT";
export const DELETE_CURRENT_WORKOUT = "DELETE_CURRENT_WORKOUT";

// Trainer/Client types
export const GET_CLIENTS = "GET_CLIENTS";
