// Auth types
export const ASYNC_START_AUTH = "ASYNC_START_AUTH";
export const ASYNC_ERROR_AUTH = "ASYNC_ERROR_AUTH";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT = "LOGOUT";

// User types
export const ASYNC_START_USER = "ASYNC_START_USER";
export const ASYNC_ERROR_USER = "ASYNC_ERROR_USER";
export const SIGNEDUP = "SIGNUP";

// Exercise Category types
export const ASYNC_START_EXERCISE_CATEGORIES =
  "ASYNC_START_EXERCISE_CATEGORIES";
export const ASYNC_ERROR_EXERCISE_CATEGORIES =
  "ASYNC_ERROR_EXERCISE_CATEGORIES";

export const GET_EXERCISE_CATEGORIES = "GET_EXERCISE_CATEGORIES";

// Exercise types
export const ASYNC_START_EXERCISES = "ASYNC_START_EXERCISES";
export const ASYNC_ERROR_EXERCISES = "ASYNC_ERROR_EXERCISES";
export const GET_EXERCISES = "GET_EXERCISES";
export const ADD_EXERCISE = "ADD_EXERCISE";

// Routine types

export const ASYNC_START_ROUTINES = "ASYNC_START_ROUTINES";
export const ASYNC_ERROR_ROUTINES = "ASYNC_ERROR_ROUTINES";
export const UPDATE_CURRENT_NEW_ROUTINE = "UPDATE_CURRENT_NEW_ROUTINE";
export const SET_CURRENT_NEW_ROUTINE = "SET_CURRENT_NEW_ROUTINE";
export const UPDATE_CURRENT_ROUTINE_TITLE = "UPDATE_CURRENT_ROUTINE_TITLE";
export const POST_NEW_ROUTINE = "POST_NEW_ROUTINE";
export const ADD_EXERCISE_TO_CURRENT_ROUTINE =
  "ADD_EXERCISE_TO_CURRENT_ROUTINE";
export const GET_ROUTINES = "GET_ROUTINES";
export const CLEAR_ROUTINE = "CLEAR_ROUTINE";

// Workout types
export const ASYNC_START_WORKOUTS = "ASYNC_START_WORKOUTS";
export const ASYNC_ERROR_WORKOUTS = "ASYNC_ERROR_WORKOUTS";
export const GET_USER_WORKOUTS = "GET_USER_WORKOUTS";
export const ADD_WORKOUT = "ADD_WORKOUT";

// Current Workout types
export const ASYNC_START_CURRENT_WORKOUT = "ASYNC_START_CURRENT_WORKOUT";
export const ASYNC_ERROR_CURRENT_WORKOUT = "ASYNC_ERROR_CURRENT_WORKOUT";
export const SET_CURRENT_WORKOUT = "SET_CURRENT_WORKOUT";
export const GET_CURRENT_WORKOUT = "GET_CURRENT_WORKOUT";
export const NO_CURRENT_WORKOUT = "NO_CURRENT_WORKOUT";
export const ADD_EXERCISE_TO_CURRENT_WORKOUT =
  "ADD_EXERCISE_TO_CURRENT_WORKOUT";
export const FINISH_WORKOUT = "FINISH_WORKOUT";
export const DELETE_CURRENT_WORKOUT = "DELETE_CURRENT_WORKOUT";
export const UPDATE_CURRENT_WORKOUT_EXERCISE =
  "UPDATE_CURRENT_WORKOUT_EXERCISE";

// Trainer/Client types
export const GET_CLIENTS = "GET_CLIENTS";
export const ASYNC_START_CLIENTS = "ASYNC_START_CLIENTS";
export const ASYNC_ERROR_CLIENTS = "ASYNC_ERROR_CLIENTS";
